name: Сборка, публикация и деплой образа в Timeweb Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      REGISTRY: ${{ vars.REGISTRY_NAME }}              # например: cr.timeweb.cloud
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}              # например: 5c69afee-intelligent-callisto/novoland
      TAG: ${{ github.sha }}
      TG_CHAT_ID: ${{ vars.TG_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}

    steps:
      - name: 📦 Получаем код из репозитория
        uses: actions/checkout@v4

      - name: 🔑 Входим в Timeweb Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.TWC_REGISTRY_USER }}
          password: ${{ secrets.TWC_REGISTRY_TOKEN }}

      - name: 🏗 Собираем Docker-образ
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG .

      - name: 🏷 Добавляем тег latest
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:$TAG $REGISTRY/$IMAGE_NAME:latest

      - name: 🚀 Публикуем образы в реестр
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$TAG
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: 📢 Отправляем уведомление в Telegram
        if: success()
        run: |
          MESSAGE="✅ Успешная сборка и публикация образа:
          \nРепозиторий: $REGISTRY
          \nОбраз: $IMAGE_NAME
          \nТеги: $TAG, latest"

          curl -s -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"
