name: Build and publish Docker image

on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags (short SHA + latest)
        id: set-tags
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          # Always push two tags: short SHA and latest
          echo "TAGS=ghcr.io/${GITHUB_REPOSITORY}:${SHORT_SHA},ghcr.io/${GITHUB_REPOSITORY}:latest" >> $GITHUB_ENV
          echo "Computed tags: $TAGS"

      - name: Build and push Docker image (sha + latest)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Redeploy novoland stack in Portainer
        env:
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
          PORTAINER_TOKEN: ${{ secrets.PORTAINER_TOKEN }}
          STACK_ID: 2
          ENDPOINT_ID: 1
        run: |
          echo "Triggering redeploy for stack novoland..."
          curl -k -X PUT \
            -H "x-api-key: $PORTAINER_TOKEN" \
            -H "Content-Type: application/json" \
            "$PORTAINER_URL/api/stacks/$STACK_ID/git/redeploy?endpointId=$ENDPOINT_ID" \
            -d '{}' -w "\nHTTP_STATUS:%{http_code}\n"
